# Array Creation

In [8]:
import numpy as np

## Create an array from a list

In [9]:
#Crear un array a partir de una lista
lista = [1, 2, 3, 4, 5]
arr1 = np.array(lista)
print(f"Array desde lista: {arr1}")

Array desde lista: [1 2 3 4 5]


## Create an array with a range of values

In [10]:
#Crear un array con un rango de valores
arr2 = np.arange(0, 10, 2) #valores de 0 a 10 con paso de 2
print(f"Array con np.arange: {arr2}")

Array con np.arange: [0 2 4 6 8]


## Create an array of zeros and ones

In [11]:
#Crear un array de ceros y unos
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))

print(f"Array de ceros:\n{zeros}")
print(f"Array de unos:\n{ones}")

Array de ceros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array de unos:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Create an identity matrix

In [12]:
#Crear una matriz identidad
identity = np.eye(3)
print(f"Matriz identidad:\n{identity}")

Matriz identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Create an array of random numbers

In [13]:
#Crear un array de números aleatorios
randomArr = np.random.rand(3, 3) #matriz 3x3 con valores aleatorios entre 0 y 1
print(f"Array aleatorio con np.random.rand:\n{randomArr}")

Array aleatorio con np.random.rand:
[[0.97170952 0.92714337 0.37787365]
 [0.18340484 0.02488135 0.74921834]
 [0.48716593 0.04411193 0.35253534]]


## Create an array with normal distribution

In [14]:
#Crear un array con distribución normal
normalArr = np.random.randn(3, 3) #matriz 3x3 con distribución normal estándar
print(f"Array con distribucion normal:\n{normalArr}")

Array con distribucion normal:
[[ 1.09954238  0.1449382   0.47306478]
 [-1.00764594 -1.88206027  1.78892369]
 [ 0.747854   -0.85165986 -0.9338296 ]]
