# Array manipulation and transformation in NumPy

In [2]:
import numpy as np

## Example data

In [3]:
#Datos de ejemplo
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Array original:\n{arr}")

Array original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose an array (swap rows and columns)

In [4]:
#Transponer un array (intercambiar filas y columnas)
transpuesta = arr.T
print(f"Transpuesta del array:\n{transpuesta}")

Transpuesta del array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Reshape an array

In [5]:
#Cambiar la forma de un array
reshapeArr = arr.reshape(1, 9) #convertir en un array de 1 fila y 9 columnas
print(f"Array despues del reshape:\n{reshapeArr}")

Array despues del reshape:
[[1 2 3 4 5 6 7 8 9]]


## Flatten an array

In [6]:
#Aplanar un array
flattenArr = arr.flatten()
print(f"Array aplanado:\n{flattenArr}")

Array aplanado:
[1 2 3 4 5 6 7 8 9]


## Concatenate arrays

In [7]:
#Concatenar arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenado = np.concatenate((arr1, arr2))
print(f"Arrays concatenados:\n{concatenado}")

Arrays concatenados:
[1 2 3 4 5 6]


## Split an array

In [10]:
#Dividir un array
splitArr = np.split(arr, 3) #Divide el array en 3 partes
print("Array dividido en 3 partes: ")
for subArr in splitArr:
    print(subArr)

Array dividido en 3 partes: 
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


## Adding and removing elements in an array

In [11]:
#Agregar y eliminar elementos en un array
arrAgregado = np.append(arr, [[10, 11, 12]], axis=0) #agregar fila
print("Array dividio en 3 partes: ")
print(arrAgregado)

arrEliminido = np.delete(arr, 1, axis=0) #eliminar segunda fila
print("Array despues de delete: ")
print(arrEliminido)

Array dividio en 3 partes: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Array despues de delete: 
[[1 2 3]
 [7 8 9]]
