# Array Creation

### Import the library

In [1]:
#Importar la libreria
import numpy as np

### Create an array from a list

In [2]:
#Crear un array a partir de una lista
lista = [1, 2, 3, 4, 5]
arr1 = np.array(lista)
print(f"Array desde lista: {arr1}")

Array desde lista: [1 2 3 4 5]


### Create an array with a range of values

In [3]:
#Crear un array con un rango de valores
arr2 = np.arange(0, 10, 2) #valores de 0 a 10 con paso de 2
print(f"\nArray con np.arange: {arr2}")


Array con np.arange: [0 2 4 6 8]


### Create an array of zeros and ones

In [4]:
#Crear un array de ceros y unos
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))

print(f"Array de ceros: {zeros}")
print(f"Array de unos: {ones}")

Array de ceros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array de unos: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Create an identity matrix

In [5]:
#Crear una matriz identidad
identity = np.eye(4)
print(f"Matriz identidad: {identity}")

Matriz identidad: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Create an array of random numbers

In [6]:
#Crear un array de numeros aleatorios
randomArr = np.random.rand(3, 3) #matriz 3x3 con valores aleatorios entre 0 y 1
print(f"Array aleatorio con np.random.rand: {randomArr}")

Array aleatorio con np.random.rand: [[0.56403789 0.77575819 0.35700293]
 [0.63803511 0.64365231 0.84668492]
 [0.35570475 0.50337574 0.30231828]]


### Create an array with normal distribution

In [7]:
#Crear un array con distribucion normal
normalArr = np.random.randn(3, 3) #matriz 3x3 con distribucion normal estandar
print(f"Array con distribucion normal: {normalArr}")

Array con distribucion normal: [[-1.56213178 -0.5675154   0.13563617]
 [ 0.03904067 -0.32966893  0.21443235]
 [ 0.47305071  0.55045954 -0.18563861]]
