# Array manipulation and transformation in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array original: ")
print(arr)

Array original: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose an array (swap rows and columns)

In [3]:
#Transponer un array (intercambiar filas y columnas)
transpuesta = arr.T
print("Transpuesta del array: ")
print(transpuesta)

Transpuesta del array: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Reshape an array

In [4]:
#Cambiar la forma de un array
reshapeArr = arr.reshape(1, 9) #convertir en un array de 1 fila y 9 columnas
print("Array despues del reshape: ")
print(reshapeArr)

Array despues del reshape: 
[[1 2 3 4 5 6 7 8 9]]


### Flatten an array

In [5]:
#Aplanar un array
flattenArr = arr.flatten()
print("Array aplanado: ")
print(flattenArr)

Array aplanado: 
[1 2 3 4 5 6 7 8 9]


### Concatenate arrays

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenado = np.concatenate((arr1, arr2))
print("Arrays concatenados: ")
print(concatenado)

Arrays concatenados: 
[1 2 3 4 5 6]


### Split an array

In [7]:
#Dividir un array
splitArr = np.split(arr, 3) #Divide el array en 3 partes
print("Array divido en 3 partes: ")
for subArr in splitArr:
    print(subArr)

Array divido en 3 partes: 
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


### Adding and removing elements in an array

In [8]:
#Agregar y eliminar elementos en un array
arrAgregado = np.append(arr, [[10, 11, 12]], axis=0) #agregar fila
print("Array dividio en 3 partes: ")
print(arrAgregado)

arrEliminido = np.delete(arr, 1, axis=0) #Eliminar segunda fila
print("Array despues de delete: ")
print(arrEliminido)

Array dividio en 3 partes: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Array despues de delete: 
[[1 2 3]
 [7 8 9]]
